mario-bermonti/mdigit_span_tasks_ema

lib/src/data_manager/data_manager.dart

- Require params required by FirebaseDB 
- Change DriftDB references to FirebaseDB
- Remove dead code

Adapt DataManager to use FirebaseDB

---

lib/src/export_data/controller/data_exporter.dart
lib/src/services/data_processor.dart
lib/src/services/run_session.dart
lib/src/services/services/export_dbs.dart
lib/src/task_list/view/task_buttons.dart

- Require FirebaseDB params
- Pass FirebaseDB params to DataManager
- Refactor names to improve consistency
- Remove dead code

Adapt processData to use FirebaseDB

---

lib/src/digit_span_tasks/config/config_dsb.dart
lib/src/digit_span_tasks/config/config_dsf.dart

improve: Shorten cognitive_tasks for testing

---

lib/src/task_list/view/task_list_page.dart

refactor: Make widgets const

---

lib/src/notifications/firebase_notifications.dart
lib/src/notifications/local_notifications.dart

Make notifications received while application is the foreground visible on android.
Closes #22

Mario-bermonti/issue22

---

pubspec.yaml

Upgrade cognitive_data and mdigits_span_tasks and improve structure of data

---

pubspec.yaml

These changes were implemented by the latest versions of the `mdigit_span_tasks` and `cognitive_data` packages so they only require upgrading to these versions.
Closes #37

Collect start and end times for each trial

---

lib/src/app_bar/app_bar.dart
lib/src/task_list/view/task_buttons.dart

These are intuitive descriptors for participants who are laypersons.
Closes #40

Present descriptive names for cognitive tasks and app bar title to participants cognitive tasks and 

---

lib/src/digit_span_tasks/task_runners/rest_instructions.dart
lib/src/digit_span_tasks/task_runners/run_dsb.dart
lib/src/digit_span_tasks/task_runners/run_dsf.dart
pubspec.yaml

Upgrading requires providing instructions for reset periods and benefit from improved 'continue buttons'.
Closes #46

Upgrade `digit_span_tasks`

---

lib/main.dart
lib/src/digit_span_tasks/config/config.dart
lib/src/digit_span_tasks/config/ds_stim.dart
lib/src/digit_span_tasks/config/stim_dsb.dart
lib/src/digit_span_tasks/config/stim_dsf.dart
lib/src/digit_span_tasks/task_runners/run_dsb.dart
lib/src/digit_span_tasks/task_runners/run_dsf.dart
lib/src/ema/run_ema_tasks.dart
lib/src/services/data_processor.dart
lib/src/services/run_session.dart
lib/src/task_list/view/task_buttons.dart

The config controller is a GetxController that contains  everything needed to config and run a cognitive task.
Closes #49

Define a config controller that is made available using dependency injection

---

.gitignore
assets/baseline_questions/educational_level.json
assets/baseline_questions/employment.json
assets/baseline_questions/gender.json
assets/baseline_questions/income.json
assets/baseline_questions/language.json
assets/baseline_questions/marital_status.json
assets/baseline_questions/sex.json
lib/main.dart
lib/src/baseline/baseline_survey_controller.dart
lib/src/baseline/baseline_survey_screen.dart
lib/src/dob_question.dart
lib/src/initial_route_manager/initial_route_manager_controller.dart
lib/src/initial_route_manager/initial_route_manager_view.dart
lib/src/routes.dart
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml
test/src/baseline/baseline_survey_controller_test.dart

We now collect baseline survey data when the app is first started. These data is only collected once for the participant.
Closes #59

Collect baseline survey data

---

lib/src/baseline/baseline_survey_screen.dart

fix: Use onSubmit in baseline survey

---

lib/src/informed_consent/consent_sections.dart

improve: Add consent section's titles into Spanish

---

lib/src/informed_consent/consent_sections.dart
lib/src/surveys/demographics_instructions.dart
lib/src/surveys/demographics_survey_controller.dart

Add instructions to demographics surveys and make adjust the consent's info to make it consistent with the survey.
Closes #81

Add instructions to demographics survey

---

lib/src/task_list/view/task_buttons.dart

This pull request includes changes to improve the UI of the task list buttons. The "Memoria de números al revés" button has been renamed to "Memoria de números inversos" and the "Memoria de números" button has been centered.
Closes #85
This pull request includes changes to improve the UI of the task list buttons. The "Memoria de números al revés" button has been renamed to "Memoria de números inversos" and the "Memoria de números" button has been centered.

Improve UI of task list buttons

---

android/app/build.gradle
docs/release.md
ios/Podfile
ios/Runner.xcodeproj/project.pbxproj
lib/src/notifications/firebase_notifications.dart
pubspec.yaml

Releasing this new version included bumping the version, updating the ema notification topic to `ema_reminders`, and optimizing dependencies.
Closes #89

Release new version for internal testing

---

ios/Runner.xcodeproj/project.pbxproj

maint: Add auto changes to ios by xcode

---

docs/design/data.md

Design the data the app will collect. This document should be updated whenever new data wants to be collected and will serve as the guide to add new app features/components.
Closes # 103

Mario-bermonti/issue103

---

.github/workflows/linting.yaml

Run `dart analyze` on push and pull requests
Closes #125

ci: Lint on pull requests

---

lib/src/app.dart
lib/src/core/notifications/remote_notifications.dart
lib/src/digit_span_tasks/task_runners/run_dsb.dart
lib/src/digit_span_tasks/task_runners/run_dsf.dart
lib/src/ema/run_ema_tasks.dart
lib/src/informed_consent/consent_screen.dart
lib/src/ui_components/instructions.dart
test/src/ema_db/datasources/firebase_datasource_test.dart
test/src/notifications/data/notifications_permission_repository_service_test.dart

Fix minor any style and formatting issues detected by `dart analyzer`.
Closes #127

maint: Fix style and formatting issues

---

.github/workflows/tests.yaml

Run tests when changes are pushed or pull requests are submitted.
Closes #129

ci: Test on push and pull requests

---

lib/src/ema/ema_instructions.dart
lib/src/ema/ema_screen.dart

Add instructions to EMA Screen using a separte widget.

improve: Add instructions to EMA screen

---

pubspec.yaml
test/src/core/ema_db/datasources/getx_datasource_test.dart
test/src/core/ema_db/fake_path_provider.dart
test/src/core/ema_db/participant/participant_repository_test.dart
test/src/core/ema_db/permissions/permission_repository_test.dart
test/src/core/ema_db/progress/progress_repository_test.dart
test/src/notifications/data/notifications_permission_repository_service_test.dart
test/src/study_progress/study_progress_service_test.dart

We fix the issues by
- properly init GetStorage in tests
- mocking getting the applications directory for GetStorage
- awaiting GetStorage  async operations complete after tests
Closes #131

test: Fix failing tests due of minor issues

---

.github/workflows/build_android.yaml
.github/workflows/build_ios.yaml
android/app/build.gradle
android/app/src/debug/AndroidManifest.xml
android/app/src/main/AndroidManifest.xml
android/app/src/profile/AndroidManifest.xml
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

Check app builds on ios and andriod on pull requests.
Closes #133

ci: Check app builds on pull requests

---

lib/src/routes.dart
lib/src/task_list/models/task_tile_model.dart
lib/src/task_list/view/pages/task_list_page.dart
lib/src/task_list/view/task_list_page.dart
lib/src/task_list/view/widgets/task_tile.dart
lib/src/task_list/viewmodels/task_list_viewmodel.dart

Changed task list's button into list tiles which were tappable in order to improve ux of tasktile.
Closes #140

Improves the tasklist ux
